homeserverUrl: "YOUR_HOMESERVER_HERE"
accessToken: "YOUR_TOKEN_HERE"

# How long back messages can be to be responded to
msBetweenResponses: 200

# Settings for controlling how logging works
# The Docker image will only consider the consoleLevel, and not write to any files.
logging:
  file: logs/matrix-bot-abstract.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5